### ISSUE TITLE
Improper caching causing dupes for offline players

### ISSUE THREAD

**Issue by Jikoo** [Jikoo/OpenInv#10]
This is a rare case. The Player loaded by the PlayerDataManager is a new object for SpecialEnderChest and SpecialPlayerInventory.

To replicate dupe/overwrite issues:

1. Open an offline player's inventory to cache it
2. Open the offline player's ender chest to cache it
3. Edit both inventories
4. Restart server to clear cached inventories (cached inventories only clear when players go offline - some retention policy would be good, the current state is bad)
5. Reopen inventories to see whichever was closed first reverted to previous state

To fix this, I'm probably going to implement a cache system similar to Guava's - while the inventory has viewers, players will be loaded. After that there will be a brief period, probably a couple minutes, where they (and the relevant inventories) remain cached in case of a re-open.
This will also allow us to further reduce redundant saves pretty simply - saving really only needs to happen when a player is removed from the cache.

**Comment by Kakifrucht** [comment]
Cool thanks.
However the armor row disappeared, what happened there?

**Comment by Jikoo** [comment]
Odd, it seemed to work fine in testing, I'll look into it

**Comment by Kakifrucht** [comment]
Fixed now, thanks alot!
