### ISSUE TITLE
Minecraft v1.19.3 support

### ISSUE THREAD

**Issue by PetyXbron** [Jikoo/OpenInv#114]
Hey guys,
I just want to ask if you could update the OpenInv plugin to support the new Minecraft version 1.19.3 [1_19_R2].

**Comment by PetyXbron** [comment]
OK. I look forward to that update. Thank you!

**Comment by Jikoo** [comment]
https://github.com/Jikoo/OpenInv/releases/tag/4.2.2
The release was copied to BukkitDev and will be available there whenever it gets approved.

**Comment by PetyXbron** [comment]
Thank you for your amazing work! Keep it up <3

**Comment by molor** [comment]
@Jikoo, in case if you also aware that 1.19.4 was released yesterday: please update to v1_19_R3.

**Comment by Jikoo** [comment]
Honestly I appreciate the heads up anyway - I don't always check Spigot. It does occur to me now that I could watch the announcements forum to get emails when updates are posted rather than rely on stumbling across someone else mentioning MC updating.
