### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by RobellaMC** [Jikoo/OpenInv#118]
I updated to the latest version of OpenInv and it stopped working. Downgraded a version and it's still happening. 

Full list of plugins: 
![image](https://user-images.githubusercontent.com/78275916/209397333-542d3408-fbb1-4365-99bb-7188df1abd28.png)

Error log from console: 
23.12 19:27:41 [Server] WARN java.lang.InstantiationException: Unable to create a new SpecialPlayerInventory
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:122)
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:194)
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:261)
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:194)
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:93)
23.12 19:27:41 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
23.12 19:27:41 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
23.12 19:27:41 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1517)
23.12 19:27:41 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485)
23.12 19:27:41 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1441)
23.12 19:27:41 [Server] WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1208)
23.12 19:27:41 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
23.12 19:27:41 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
23.12 19:27:41 [Server] WARN Caused by: java.lang.reflect.InvocationTargetException
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:123)
23.12 19:27:41 [Server] WARN ... 12 more
23.12 19:27:41 [Server] WARN Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.world.entity.player.EntityHuman.fA()'
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.internal.v1_19_R1.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:71)
23.12 19:27:41 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23.12 19:27:41 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
23.12 19:27:41 [Server] WARN at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23.12 19:27:41 [Server] WARN at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
23.12 19:27:41 [Server] WARN at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.InternalAccessor.createObject(InternalAccessor.java:95)
23.12 19:27:41 [Server] WARN at OpenInv (3).jar//com.lishid.openinv.InternalAccessor.createSpecialInventory(InternalAccessor.java:120)
23.12 19:27:41 [Server] WARN ... 12 more

**Comment by Jikoo** [comment]
Use 4.2.0 for 1.19. There was no NMS revision bump for the breaking 1,19.1 update.
