### ISSUE TITLE
OpenEnder Perm not working anymore.

### ISSUE THREAD

**Issue by Tosfoy** [Jikoo/OpenInv#119]
Hello! We're having an issue where the perm to open enderchests do not work anymore!
![image](https://user-images.githubusercontent.com/58991099/209415508-9490dfac-3614-464f-82ae-4b08acfb4ba1.png)

We've redone the entire perms for openinv and the issue is still here.
No errors in console, I do not know when this broke

![image](https://user-images.githubusercontent.com/58991099/209415581-d80304d1-6a13-4ac4-81d3-185006292be9.png)

**Comment by Jikoo** [comment]
You're missing `OpenInv.openenderall`.

**Comment by Tosfoy** [comment]
Lol. Just at the moment I edit the thread. Thank you tho! Fast response :)
