### ISSUE TITLE
Bug removed inventory

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Jikoo/OpenInv#120]
Good morning, I have detected an error when using OpenInv with EssentialsX (https://ci.ender.zone/job/EssentialsX/) I have both updated to their latest version.

To reproduce the bug you have to use spectator mode. Write /gmsp and disconnect from the game, if another "moderator" accesses your inventory with /openinv "player" when this player re-enters your inventory will be empty.

Greetings and thanks for the support and for the plugin.

**Comment by Jikoo** [comment]
Essentials' gamemode command does not do anything beyond change gamemode, and OI/Minecraft in general doesn't handle spectators differently. If you're experiencing inventory inaccuracy or loss, please make sure you're not running some kind of per-gamemode/per-world/cross-server inventory system.

**Comment by Mundo-Minecraft** [comment]
Sorry, I haven't given you all the information. I forgot to mention that I also use perworldinventory (https://github.com/EbonJaeger/perworldinventory-kt)

This happens to me in version 1.19.3. Perworldinventory does not require updating but both essentials and openinv did update and that was when the errors started. I have loaded old versions of essentialsx and this error keeps happening.

The error is as commented, if you write /gmsp you disconnect and connect there is no error. But if when you are offline you access with openinv when the user logs back in he has no inventory.

**Comment by Jikoo** [comment]
You should be using your inventory management plugin's method for offline access - OI only supports vanilla inventory.
