### ISSUE TITLE
OpenInv in certain worlds

### ISSUE THREAD

**Issue by elapu** [Jikoo/OpenInv#145]
I am unable to open a player's inventory in certain worlds, I use multiverse inventories and some players learned to abuse this by putting their items in a inventory in a world that they are not in making it impossible to find that item until they return to that world.

**Comment by Jikoo** [comment]
See lishid/OpenInv#122, not really possible without adding a tremendous support burden. Ask your multi-inventory plugin to add a command to open its files in an editor.
