### ISSUE TITLE
Dupe error

### ISSUE THREAD

**Issue by USBCharger** [Jikoo/OpenInv#154]
A few days ago I was checking some players inventories, and they started to dupe in a weird way. The hot bar seems to dupe once at a time, in a vertical manner, per opening of a player's inventory. It's hard to describe the situation better than that. I am running Purpur 1.20.1-2004, and was running the latest version of openinv.

**Comment by Jikoo** [comment]
I'm not able to reproduce this. Have you been able to get this to occur without other plugins? Are you in creative when the unexpected inventory behavior occurs?
