### ISSUE TITLE
First join date resetting

### ISSUE THREAD

**Issue by Stormystic** [Jikoo/OpenInv#16]
Running /oi on a player will reset their firstPlayed NBT tag to the current date. I first joined my server way back in March 2019. I ran /oi on myself and after relogging it now incorrectly shows that I first joined 4/10/2021, today.

**Comment by Jikoo** [comment]
Interesting. My guess is that the first join date is a Bukkit-specific tag, so MC doesn't load it when the player's NBT is read.

We already have special handling in place for vehicles, so this is definitely a pretty easy fix.
