### ISSUE TITLE
using openinv duplicates peoples' inventories

### ISSUE THREAD

**Issue by nuttapillar** [Jikoo/OpenInv#167]
I'm running this in Purpur 1.20.2. and often when i use openinv to view someone's inv, it duplicates everything

**Comment by Jikoo** [comment]
Can't reproduce that on Paper, going to need more info. OI version? Server build? Have you tried testing without other plugins? Is this your own inventory only? Are you in creative? When you say "duplicates" what exactly do you mean? A screenshot would be helpful.
