### ISSUE TITLE
Inventory getting scrambled?

### ISSUE THREAD

**Issue by LaughNgamez** [Jikoo/OpenInv#172]
For some reason on my server when I run /openinv username it flips the players armour and puts their boots on their head. Every other item in their inventory is scrambled too lol. 
![2023-12-08_13 00 40](https://github.com/Jikoo/OpenInv/assets/12781929/699dc568-d3ef-4771-83c8-53fd51d04f38)
![2023-12-08_13 00 45](https://github.com/Jikoo/OpenInv/assets/12781929/388164e3-af80-4de4-9a46-84a3f395de3e)

**Comment by Jikoo** [comment]
Please provide the output of `/version` and `/version openinv` - was unable to reproduce this locally.

**Comment by LaughNgamez** [comment]
Paper 1.20.2 & OpenInv 4.4.1

![2023-12-09_09 19 50](https://github.com/Jikoo/OpenInv/assets/12781929/8a03fc14-cef8-406b-8c44-3c343d9b3027)

**Comment by LaughNgamez** [comment]
Any update? Not sure why this happens

**Comment by Jikoo** [comment]
Nope. I just got out of finals week and am dealing with finishing a cross-country move, I am not in a position to debug this at the moment.

If you're looking to make progress, try with only OpenInv installed. If the inventory is not scrambled, it's a plugin conflict and you'll have to resolve that yourself. If it is, the slot ordering changed and I need to compensate for that.

**Comment by Jikoo** [comment]
Not able to reproduce this. I tried various configurations of user online/offline/logging in while open/reopening/closed and all behaved as expected. Unfortunately, this is likely a plugin conflict and you'll need to figure out which one it is on your own. You can remove half your plugins at a time to narrow it down faster.
