### ISSUE TITLE
[Feature Request] Geyser Support

### ISSUE THREAD

**Issue by Romvnly-Gaming** [Jikoo/OpenInv#18]
Hi, I'm currently using Geyser and OpenInv together however I cannot open Bedrock player's inventories.

Can you please add Geyser Support?

Popular Geyser Prefixes: .,  *

![javaw_LbW9qlahix](https://user-images.githubusercontent.com/62443489/115552945-dcdb4700-a27a-11eb-9ce8-15bff8bc11ad.png)

**Comment by Jikoo** [comment]
See https://github.com/lishid/OpenInv/issues/163#issuecomment-720133418 - make sure you are including the special character at the start of the name. If that fails, please attempt to open their inventory using their UUID.

As it stands, no one encountering this issue has gotten back to me with any additional information. I briefly looked into Geyser and it appeared to store Bedrock players in the exact same fashion as regular players, so I'm inclined to believe the commenter who said it's user error.

**Comment by Romvnly-Gaming** [comment]
Well, for some reason it's not working. It's not exactly optimal to have staff putting in UUIDs to check a player's inventory.

https://user-images.githubusercontent.com/62443489/115583710-24bc9700-a298-11eb-8376-17f6881af27d.mp4

**Comment by Jikoo** [comment]
I'm willing to look into it again, but you're going to have to work with me on it to some degree - I don't have a Bedrock account and I don't intend to figure out how to set up Geyser locally.

I need a player data file belonging to a Bedrock user to inspect - they should be stored in `world/playerdata/<their uuid>.dat`. After I poke through that I may need you to run a build with additional debug information printed during the player identification process.

**Comment by Romvnly-Gaming** [comment]
Alright, I'm willing to work with you. Lemme grab my playerdata
http://www.mediafire.com/view/osmkrz4jx3mbm0a

**Comment by Jikoo** [comment]
Ok, the last known name is set. That's good, I can work with that. I have to assume Geyser messes with the usercache, so that's the next step. If you would, please ensure that your usercache.json contains an entry for that user. It should look something like this:
```JSON
{
  "name":"*RomvnlyYT",
  "uuid":"00000000-0000-0000-0009-00000da0f8ce",
  "expiresOn":"some date"
}
```
The usercache isn't technically relevant to the problem - how Geyser provides names for the players it injects is - but it's a good place to start for finding behavior that's out of the norm.

**Comment by Romvnly-Gaming** [comment]
```json
{
  "name": "*RomvnlyYT",
  "uuid": "00000000-0000-0000-0009-00000da0f8ce",
  "expiresOn": "2021-05-15 12:46:25 -0400"
}
```
yep, it has it.

**Comment by Jikoo** [comment]
I see - you must be using FloodGate with Geyser, so your server's in online mode, correct?

**Comment by Jikoo** [comment]
I've pushed a commit removing name validation for servers in online mode. When the run finishes, you can download the dev build from it [here](https://github.com/Jikoo/OpenInv/actions/runs/771677809) - the jar is inside the dist zip that will be at the bottom of the page.

**Comment by Romvnly-Gaming** [comment]
> 
> 
> I see - you must be using FloodGate with Geyser, so your server's in online mode, correct?

Yes 

> 
> 
> I've pushed a commit removing name validation for servers in online mode. When the run finishes, you can download the dev build from it [here](https://github.com/Jikoo/OpenInv/actions/runs/771677809) - the jar is inside the dist zip that will be at the bottom of the page.

Thanks! 😃

**Comment by Romvnly-Gaming** [comment]
And confirmed, the build works. Thanks for such a speedy response!
![javaw_aAfwBwIj4W](https://user-images.githubusercontent.com/62443489/115606071-40806700-a2b1-11eb-9e54-0049e0e7c8f3.png)
