### ISSUE TITLE
Searchcontainer doesn't work outside render distance

### ISSUE THREAD

**Issue by jedijacob2210** [Jikoo/OpenInv#188]
If I can't see the chest, it straight up doesn't return, even if it is absolutely guaranteed to be there.
At roughly 12 chunks it no longer works.

**Comment by Jikoo** [comment]
Searching a 12 chunk radius means a 25x25 of chunks loaded. Say your ticking distance is 8 chunks, you load 17x17 chunks. That's 625-289=336 chunks freshly loaded by the command. That's pretty obscene, and it gets orders of magnitude worse the higher the radius goes. You're asking to crash your server. That said, your server, your choice: https://github.com/Jikoo/OpenInv/blob/d887ff8eae2d1e89f37deef7eb403f44639dd430/plugin/src/main/resources/config.yml#L6-L7

I say this with relative regularity: If you are trying to locate an object, use a tracking plugin like Prism or CoreProtect. Their searches are global, async, and give you context/blame. OpenInv's searches are local and do not give you any context. I have, on multiple occasions while managing servers, witnessed staff wrongly accuse someone based on incomplete OI information only to find out after inspection of Prism logs that someone else was the culprit.

In terms of workload management, I would also advise you to just install a protection plugin and tell players they're responsible for protecting their stuff, tough cookies if they don't. That was a huge stress reducer for me.
