### ISSUE TITLE
Can no longer edit inventory in /oi.

### ISSUE THREAD

**Issue by temoya1** [Jikoo/OpenInv#19]
When this plugin is combined with SaberFactions or Vault, it is no longer possible to edit the inventory by /oi.

SaberFactions
https://www.spigotmc.org/resources/saberfactions-1-8-1-16-x-discord-saber-pw-the-complete-factions-solution.69771/
Vault
https://www.spigotmc.org/resources/vault.34315/

**Comment by Jikoo** [comment]
That's a SaberFactions issue - they blindly cancel interaction based on invetory name. See https://github.com/lishid/OpenInv/issues/167#issuecomment-743696206 - you can change the name format to circumvent this.
