### ISSUE TITLE
Items are duplicated when moving them using OpenInv

### ISSUE THREAD

**Issue by FrozenSoda** [Jikoo/OpenInv#199]
Since OpenInv 4.4.4, when you take items from an offline player's inventory, they reappear the next time you open their inventory. The issue does not seem to appear in 4.4.3. Using Paper 1.20.4 build 496.

Reproduction:
1. Open an offline player's inventory using `/openinv PLAYER_NAME_HERE`
2. Move an item from the player's inventory to your own.
3. Close the player's inventory with ESC and open it again using `/openinv PLAYER_NAME_HERE`
4. The item will be back in the player's inventory while also staying in your own, meaning it has been duplicated.

**Comment by Jikoo** [comment]
Thanks. Looks like the root of the issue I ran into with the 1.20.6 update was around for a longer while than I thought. Cutting 4.4.5 for this, but you can stick with 4.4.3 unless you're using a specific few plugins that store their data in non-PDC NBT tags on the player.
