### ISSUE TITLE
OpenInv v4.1.6 /oe Is broken

### ISSUE THREAD

**Issue by ZeroTwosGF** [Jikoo/OpenInv#22]
`17.05 16:05:49 [Server] INFO [06:05:49 INFO]: ZeroTwosGF issued server command: /oe ZeroTwosGF
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: java.lang.InstantiationException: Unable to create a new ISpecialEnderChest: null
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at com.lishid.openinv.util.InternalAccessor.newSpecialEnderChest(InternalAccessor.java:196)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at com.lishid.openinv.OpenInv.getSpecialEnderChest(OpenInv.java:216)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:165)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:462)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
17.05 16:05:49 [Server] Startup [06:05:49 WARN]: at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by Jikoo** [comment]
Your server implementation is some kind of Forge-Bukkit hybrid that does not provide Spigot's NMS mappings.
