### ISSUE TITLE
When an OpenInv inventory is open, handling InventoryClickEvent for other plugins fail

### ISSUE THREAD

**Issue by Brokkonaut** [Jikoo/OpenInv#238]
When having an OpenInv inventory open (in this case the own player inventory), and clicking in the inventory several other plugins fail, because InventoryClickEvent.getClickedInventory() does throw an exception. The stack trace below is just an example from WorldGuard, but about 10 more plugins on our servers throw the same exception.

https://cpaste.de/cuvigabepi.apache

**Comment by Jikoo** [comment]
Could you please try with a more recent build and let me know if you still have issues? I made several improvements to views a little after 5.0.0 released.

This should be specific to the player's own inventory, because that view is a view of a subsection of a larger inventory.

**Comment by Jikoo** [comment]
Ah, found it. The problem is that OI rounds the slot count of the upper inventory out to an even number, so when CB counts slots it is a couple short.

**Comment by Brokkonaut** [comment]
Thanks for the quick fix 👍
