### ISSUE TITLE
Paper: Can no longer edit other peoples' inventories or view Ender Chests

### ISSUE THREAD

**Issue by bobatealee** [Jikoo/OpenInv#239]
Server: Paper 1.21.1 `#3`
Plugin: OpenInv v5.1.1

I am opped, and this worked on the previous version on Paper 1.21 `#127` (5.0.0). Explicitly giving the permissions to do these via LuckPerms does nothing. Ender Chests are white stained glass panes, other peoples' inventories are uneditable.

**Comment by Jikoo** [comment]
Unable to reproduce.
![image](https://github.com/user-attachments/assets/6d59422e-06d0-474b-8036-7f09ca1e442e)

**Comment by bobatealee** [comment]
New config option `equal-access` is set to `view` by default, causing this behavior. Previous behavior was `allow`.

**Comment by Jikoo** [comment]
Even with view default, you should never see OI adding panes to ender chests. Will update the patch notes to make the new default clearer though 👍
