### ISSUE TITLE
Jitpack build failed

### ISSUE THREAD

**Issue by tanyaofei** [Jikoo/OpenInv#242]
https://jitpack.io/com/github/jikoo/OpenInv/5.1.1/build.log

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OpenInv 5.1.1:
[INFO] 
[INFO] OpenInv ............................................ SUCCESS [  1.264 s]
[INFO] OpenInvAPI ......................................... FAILURE [  4.406 s]
[INFO] openinvcommon ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.740 s
[INFO] Finished at: 2024-08-10T19:41:00Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project openinvapi: The plugin org.apache.maven.plugins:maven-compiler-plugin:3.13.0 requires Maven version 3.6.3 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openinvapi
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: com.lishid:openinvparent:5.1.1
2024-08-10T19:41:03.569172371Z
Exit code: 0

**Comment by Jikoo** [comment]
`7b504971b1` appears to have produced the correct artifacts, so you should be good to use that for the version. No idea why JitPack is reporting successes for the failing builds.
