### ISSUE TITLE
RP 1.21.3+1.21.4

### ISSUE THREAD

**Issue by Boy0000** [Jikoo/OpenInv#263]
You can easily support both formats by keeping the overrides as always in the `assets/minecarft/models/item/paper.json` btu also use the new format for the `assets/minecraft/items/paper.json`
The client just ignores the stuff it doesnt need
Alternatively you can make an "overlay folder" where you override and add the new files

Tldr you can support both packs 👍 lmk if you want help with it

[wiki](https://minecraft.wiki/w/Pack.mcmeta)
![image](https://github.com/user-attachments/assets/52364fc0-cf16-41b5-8508-3442a682250e)

**Comment by Jikoo** [comment]
Oh, awesome, thank you! Learning new things all the time. I'll take a stab at it, and if I can't manage to figure it out I'll give you a shout.
