### ISSUE TITLE
1.17 version crashing the server when openender

### ISSUE THREAD

**Issue by Solmester** [Jikoo/OpenInv#27]
When running /openender the server crashes, and resulted in me having to remove openinv to continue.
Crashfile:
[crash-2021-06-13_11.05.54-server.txt](https://github.com/Jikoo/OpenInv/files/6643800/crash-2021-06-13_11.05.54-server.txt)

**Comment by Jikoo** [comment]
Update Spigot.

Why would you update plugins and not update the server itself? That inventory bug was fixed before OpenInv was released.

**Comment by Solmester** [comment]
I am currently running the newest spigot version released.

**Comment by Jikoo** [comment]
No you're not. You're running 3104. Latest is 3133.
