### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [Jikoo/OpenInv#33]
Running Airplane-Purpur version git-Airplane-"6f3677e" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
https://nekobin.com/tupucaxeto

**Comment by Jikoo** [comment]
Wacky, wonder what weird implementation they're using - we specifically use an iterator there to avoid that very problem.

**Comment by LucidAPs** [comment]
To be fair that error is really rare and i've never seen it before. So it's not like it's spamming the console.

**Comment by Jikoo** [comment]
It should only occur when someone who doesn't have permission for cross-world viewing has an inventory open and gets booted from it. Simple enough fix and it makes the code cleaner, so a good thing to address all around. 👍
