### ISSUE TITLE
SilentChest auto OFF.

### ISSUE THREAD

**Issue by WolfyRed** [Jikoo/OpenInv#40]
Is there a way to set SilentChest to automatically be turned OFF when joining or starting the server?

That way you have to manually type /sc to turn it back on.

**Comment by Jikoo** [comment]
Boy I wish, would remove half of the bad admins abusing it all the time :\ That's something I've been toying with for a while.

**Comment by WolfyRed** [comment]
I just removed the permissions. Tell me if you find a fix or something, k?

**Comment by Jikoo** [comment]
Oh, no, it's a design choice of the original OI that I'm not a fan of, not something that's hard to change. Unfortunately, OI is on the backburner for me right now, working on a rewrite featuring actual unit testing for one of my other plugins in my spare time.
