### ISSUE TITLE
OpenInv last 4 slots

### ISSUE THREAD

**Issue by WolfyRed** [Jikoo/OpenInv#41]
This is more of a recommendation. Since you have every single slot in the player's inventory, like the off-hand and armor slots, and there's only 4 empty slots left, I have an idea.

Why not use those 4 empty slots for the player's 2x2 inventory crafting slots? They're technically inventory slots, and stuff can be stored in them temporarily. Plus, those are 4 slots, just like the last 4 slots in the OpenInv GUI.

Does it sound good?

**Comment by Jikoo** [comment]
Displaying the crafting grid is a horrendous PITA, [tried it once](https://github.com/lishid/OpenInv/tree/feature/cursorcrafting).

The extra slots are not able to be used for temporary storage - items placed in them are immediately dropped as the player whose inventory is being edited.
