### ISSUE TITLE
Allow `openinv.exempt` to work for enderchests as well

### ISSUE THREAD

**Issue by baailey** [Jikoo/OpenInv#42]
Unsure if a bug or intentional, however, I'd like the permission `openinv.exempt` to also apply to enderchests. Though, a separate permission for making enderchests exempt works too if you'd prefer. Thanks.

**Comment by Jikoo** [comment]
It does, `/openinv` and `/openender` run slight variations of the same command code.
https://github.com/Jikoo/OpenInv/blob/2f36a4d4dca7966e1cc704d91647a2c91bace132/plugin/src/main/java/com/lishid/openinv/commands/OpenInvCommand.java#L142-L148
