### ISSUE TITLE
TabCompletion w/o operator status.

### ISSUE THREAD

**Issue by zhenaxel** [Jikoo/OpenInv#49]
If the player is not an operator, no players appear in the tab when entering `/open `.

Without OP:
> 
![изображение](https://user-images.githubusercontent.com/73360620/142044167-19976f66-cbd6-4185-8931-c74abff20f52.png)

With OP:
![изображение](https://user-images.githubusercontent.com/73360620/142044276-13f921e8-c017-49ef-8347-fdd76b86b8d7.png)

At the same time, players without OP, have `openinv.*`.

**Comment by Jikoo** [comment]
Cannot reproduce. Please try on a clean installation of only OI. Also would need things like server and OI version. Also, bear in mind that OI's permissions are capitalized, and some permission plugins are case sensitive. You may have misconfigured your permissions as a result.

For testing without any plugins other than OI, you can add this entry to your permissions.yml:
```yaml
basic:
  default: true
  children:
  - OpenInv.*
```
