### ISSUE TITLE
[Suggestion] Language Translation File Support.

### ISSUE THREAD

**Issue by hoehoetvhss** [Jikoo/OpenInv#50]
I translated to use your plug-in by translating Korean.

But it didn't work.

I think the owner should add a language translation system.

**Comment by Jikoo** [comment]
Please make sure your client language is set to Korean and that you have named the Korean translation the appropriate name for the Korean translation.

**Comment by Jikoo** [comment]
Note that this means you should make a file named `ko_kr.yml` and put your translations in that. Please refer to https://minecraft.fandom.com/wiki/Language for locale codes.
