### ISSUE TITLE
openender player name

### ISSUE THREAD

**Issue by seema84** [Jikoo/OpenInv#51]
Openinv Version: 4.1.8
Paper Version: 1.17.1 Build 386

The player name is not displayed at _/openender name_.

![45](https://user-images.githubusercontent.com/2832339/142765967-4f201067-f15e-441c-adba-8c2e5289af96.png)

**Comment by Jikoo** [comment]
This was fixed [a while ago](https://github.com/Jikoo/OpenInv/commit/34e7252d77b15b111db4f2e91ed01f546ded229f#diff-935f8312167f8a84e8591d8b55cd8c05218df9b47f00e55ef4e9d735d7ee0595). Unfortunately, as the language key did not change, you will need to manually fix it in your `en_us.yml` - the string should have been `%player%` but it was `%Player`. Alternately, if you have not modified it, you can safely delete it and let it regenerate.

**Comment by seema84** [comment]
All right, thanks for the information. Have a great day.
