### ISSUE TITLE
Support 1.18

### ISSUE THREAD

**Issue by alexchandel** [Jikoo/OpenInv#52]
Please add 1.18 (or v1_18_R1) to the supported versions.

**Comment by Jikoo** [comment]
Please try a dev build. I have not yet had time to test, but since mappings appear identical it is unlikely anything broke.

**Comment by Jikoo** [comment]
You can find the 1.18 dev build in the Actions run for the master branch [here](https://github.com/Jikoo/OpenInv/actions/runs/1496046886). Download the `dist` artifact - the zip file should contain a functional OpenInv.jar

**Comment by Jikoo** [comment]
At this point I do not recommend people using the dev build - I've started testing and have discovered numerous issues.

**Comment by Jikoo** [comment]
https://github.com/Jikoo/OpenInv/releases/tag/4.1.9
