### ISSUE TITLE
[1.12.2] Empty inventory + error

### ISSUE THREAD

**Issue by Quenteez** [Jikoo/OpenInv#62]
When I try to open any of the inventory with a command (ender, normal, my own, someone else's).
There's nothing there. However, for example, if I use the native command from EssentialsX - **/invsee PLAYER**. Then the player's inventory will really show me.
But EssentialsX doesn't suit me, because it doesn't know how to view offline players' inventories.

I don't know, but maybe it has something to do with Java 11. Because when the server core was running on Java 8, there were no problems with the plugin.

OpenInv version is **3.3.5**.
Spigot version is "**This server is running CraftBukkit version git-Spigot-4bd94dc-3a482bd (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**"
**Log:** https://pastebin.com/My3mbGBG

**Comment by Jikoo** [comment]
See lishid#173.
