### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by Bewildereds** [Jikoo/OpenInv#63]
I know you updated to 1.18.2, but there's no official .jar we can download right now. Did you forget or did we have to wait a bit longer?

**Comment by Jikoo** [comment]
I have not made time to test functionality. You can download builds from the Actions run as always - navigate to the run, scroll down a little to the artifacts section, and download and unzip the `dist` artifact.

In this case, [this artifact](https://github.com/Jikoo/OpenInv/suites/5483593206/artifacts/175009490).

**Comment by Jikoo** [comment]
https://github.com/Jikoo/OpenInv/releases/tag/4.1.10
