### ISSUE TITLE
Issue getting OpenInv to run

### ISSUE THREAD

**Issue by LaughNgamez** [Jikoo/OpenInv#68]
Hello, thanks for keeping this great plugin going.

I've been trying to get OpenInv to run on my server after getting back to Minecraft. I'm running 1.12 base version with ViaVersion & Geyser support but can't get the plugin to work.

The plugin boots but only opens a blank inventory and gives this error when trying to run.
https://pastebin.com/ecN3zkVq

Thanks!

**Comment by Jikoo** [comment]
See lishid#173.
