### ISSUE TITLE
Add own enderchest?

### ISSUE THREAD

**Issue by msmanui** [Jikoo/OpenInv#69]
Adding the possibility to edit your own enderchest but not others when you do /openender
This is feature of EssentialsX but it would be great to add it to OpenInv

**Comment by Jikoo** [comment]
Just don't give users the node `OpenInv.openenderall`.

**Comment by msmanui** [comment]
> Just don't give users the node `OpenInv.openenderall`.

Well but i want them to have access to see other enderchest and as well editing only their own... Like essentials.

**Comment by Jikoo** [comment]
Ah. That you can't do currently, yes. Given that it allows them to load player data from disk I'm not sure it's a great idea, but I guess there are offline-blocking nodes as well.

**Comment by msmanui** [comment]
So what is the resolution? You can add it?

**Comment by Jikoo** [comment]
Well, it's not really a resolution or the issue would be closed, but yes, it's possible to add.

That said, while it is an accepted enhancement request, I generally only work on projects when necessary or feeling excited about them, so it may be a while. The issue will be closed when a resolution is in place, so if you're watching it you'll receive an email notification or whatnot depending on account settings.
