### ISSUE TITLE
Can't access new players inv

### ISSUE THREAD

**Issue by Kakifrucht** [Jikoo/OpenInv#7]
A new player that joined the server couldn't be inv specced, it showed the "Player not found!" message.
Not sure if this happens always, I will do some further testing.

**Comment by Jikoo** [comment]
Whoops, that's a simple fix, will have a build out shortly.

**Comment by Kakifrucht** [comment]
:+1:

**Comment by Kakifrucht** [comment]
nice, could you tag a release?

**Comment by Jikoo** [comment]
Just built and uploaded, should be all set
