### ISSUE TITLE
Openender + Delete

### ISSUE THREAD

**Issue by BrandonT80** [Jikoo/OpenInv#73]
If a staff member uses /openender on an offline player, and then logs out, that persons enderchest gets copied into the staff who opened it.

**Comment by Jikoo** [comment]
Cannot reproduce. Ensure that they are not confused by the search history functionality - `/oe` with no parameters opens the last ender chest you accessed. It does not open your own ender chest unless you have not opened anyone else's ender chest prior to that. Search history persists across logouts but not across server restarts.
