### ISSUE TITLE
Changes to inv are not persisting

### ISSUE THREAD

**Issue by DestinTech** [Jikoo/OpenInv#80]
Hey there, there seems to be an issue with /openinv with offline players. The inventory items I remove are back in the players inventory a few minutes after I remove them. Any help would be appreciated, thanks!

**Comment by Jikoo** [comment]
Have you changed `settings.disable-saving` to true? OpenInv does not save edits to offline players if that option is enabled. Otherwise, make sure there are no errors in your console (`Failed to save player data for <name>`). If the console is empty and saving is enabled, this is probably an issue with another plugin overwriting OpenInv's edits.

**Comment by DestinTech** [comment]
After some investigation, it's a compatibility issue with the my_worlds plugin. Myworlds allows separate inventories for different worlds (for example, a separate creative world, or a spawn world).

It has a setting that allows split inventories and I had configured the creative world to have a separate inventory. 
Openinv was accessing the inventory of the creative world. In that world I have non-persistent inventories. 

Problem solved, blocked the creative world for now.
Is it possible for this plugin compatibility issue to be looked in to though? I'm not sure how possible a fix is for this.

**Comment by Jikoo** [comment]
If a plugin modifies inventories on a per-world basis etc., OpenInv does not know how to access and read their files. It's on them to provide an editor. OpenInv just reads the player's current inventory from disk using Minecraft's internals. There are way too many per-world inventory plugins for me personally to consider offering support, it's a colossal burden.
