### ISSUE TITLE
Different worlds/different inventories

### ISSUE THREAD

**Issue by melaniebeedot** [Jikoo/OpenInv#87]
Would there be a way to access different inventories of different worlds? We have a creative world that has a separate inventory from our survival worlds, and our minigames world also has a separate inventory from all the rest. Currently we can only /oi or /oe the inventory/enderchest of the world the player is currently in/where they logged out.

**Comment by Jikoo** [comment]
See lishid#122, not really possible without adding a tremendous support burden. Ask your multi-inventory plugin to add a command to open its files in an editor.
